In [1]:
import pandas as pd

In [2]:
# dataframes - excel, csv

In [3]:
# excel 
# pip install openpyxl
# df= pd.read_excel('filename.xlsx')

In [4]:
cars= pd.read_csv('used_cars_data.csv')
cars.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [5]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

In [6]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [14]:
engine_index_null= cars[cars.loc[:,'Engine'].isnull()].index

In [15]:
engine_index_null

Index([ 194,  208,  733,  749, 1294, 1327, 1385, 1460, 2074, 2096, 2264, 2325,
       2335, 2530, 2542, 2623, 2668, 2737, 2780, 2842, 3272, 3404, 3520, 3522,
       3810, 4011, 4152, 4229, 4577, 4604, 4697, 4712, 4952, 5015, 5185, 5270,
       6042, 6541, 6544, 6633, 6643, 6651, 6677, 6685, 6880, 6902],
      dtype='int64')

In [18]:
cars.drop(engine_index_null, axis=0, inplace=True)

In [19]:
cars.shape

(7207, 14)

In [20]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                  0
Power                   0
Seats                   7
New_Price            6201
Price                1224
dtype: int64

In [21]:
seats_index_null= cars[cars.loc[:,'Seats'].isnull()].index

In [22]:
cars.drop(seats_index_null, axis=0, inplace=True)

In [23]:
cars.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                  0
Power                   0
Seats                   0
New_Price            6194
Price                1223
dtype: int64

In [25]:
cars.drop('New_Price',axis=1, inplace=True)

In [27]:
cars.shape

(7200, 13)

In [28]:
cars.Transmission.value_counts()

Transmission
Manual       5163
Automatic    2037
Name: count, dtype: int64

In [33]:
cars[(cars.Transmission=="Automatic") & (cars.Year==2018)]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
92,92,Audi A6 2011-2015 35 TDI Premium,Coimbatore,2018,48367,Diesel,Automatic,First,17.68 kmpl,1968 CC,174.33 bhp,5.0,39.58
191,191,Land Rover Range Rover 2.2L Dynamic,Coimbatore,2018,36091,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,55.76
224,224,Mercedes-Benz New C-Class C 220d Avantgarde Ed...,Coimbatore,2018,29161,Diesel,Automatic,First,19.27 kmpl,2143 CC,167.62 bhp,5.0,39.41
255,255,Hyundai Tucson 2.0 e-VGT 2WD AT GLS,Kochi,2018,51346,Diesel,Automatic,First,16.38 kmpl,1995 CC,183 bhp,5.0,21.99
282,282,Audi Q7 3.0 TDI Quattro Technology,Kochi,2018,11287,Diesel,Automatic,First,12.07 kmpl,2967 CC,241.4 bhp,7.0,70.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7080,7080,Honda Jazz 1.2 V CVT i VTEC,Coimbatore,2018,36611,Petrol,Automatic,First,19.0 kmpl,1199 CC,88.7 bhp,5.0,NaN
7144,7144,Maruti Vitara Brezza ZDi AMT,Coimbatore,2018,57804,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN
7158,7158,Hyundai Creta 1.6 SX Plus Petrol Automatic,Coimbatore,2018,32746,Petrol,Automatic,First,13.0 kmpl,1591 CC,121.3 bhp,5.0,NaN
7184,7184,Hyundai Verna VTVT 1.6 AT SX Option,Mumbai,2018,18980,Petrol,Automatic,First,17.0 kmpl,1591 CC,121.3 bhp,5.0,NaN
7218,7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,NaN

In [34]:
titanic= pd.read_csv('Titanic-Dataset.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [36]:
titanic.shape

(891, 12)

In [38]:
titanic.drop('Cabin', axis=1, inplace=True)

In [40]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [41]:
titanic[titanic.loc[:,'Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S

In [42]:
titanic.Age.mean()

29.69911764705882

In [43]:
titanic.Age.min()

0.42

In [44]:
titanic.Age.max()

80.0

In [56]:
s1=pd.Series([12,13,45,67,90])
s1

0    12
1    13
2    45
3    67
4    90
dtype: int64

In [52]:
s1.drop(3)

0    12
1    13
2    45
4    90
dtype: int64

In [57]:
s1.drop(labels=2, inplace=True)

In [54]:
s1

0    12
1    13
3    67
4    90
dtype: int64